# #aws_region  = "us-east-1"
# #db_name     = "quickdb"
# #db_username = "postgres"
# #db_password = "changeme123"
# region       = "us-east-1"
# vpc_cidr     = "10.0.0.0/16"
# cluster_name = "my-eks-cluster"
